version: "3.7"

services:
  traefik:
    image: traefik:2.7
    container_name: "traefik"
    restart: always
    hostname: 'traefik.$DOMAIN'
    environment:
      - CLOUDFLARE_EMAIL=$CLOUDFLARE_EMAIL
      - CLOUDFLARE_API_KEY=$CLOUDFLARE_API_KEY
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/acme/acme.json:/etc/traefik/acme.json"
      - "./traefik/log/access.log:/etc/traefik/log/access.log"
      - "./traefik/log/traefik.log:/etc/traefik/log/traefik.log"
      - "./traefik/config:/etc/traefik/config/"
    networks:
      - "proxy"
    labels:
      - "traefik.enable=true"
      ## Routers Rules
      - "traefik.http.routers.traefik.rule=Host(`traefik.$DOMAIN`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.tls=true"
      ## Middlewares Rules
      - "traefik.http.routers.traefik.middlewares=chain-basic-auth@file"
      ## Services Rules
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  proxy:
    external: true