# generated 2022-08-07, Mozilla Guideline v5.6, Traefik 2.1.2, modern configuration
# https://ssl-config.mozilla.org/#server=traefik&version=2.1.2&config=modern&guideline=5.6
# Supports Firefox 63, Android 10.0, Chrome 70, Edge 75, Java 11, OpenSSL 1.1.1, Opera 57, and Safari 12.1

[http.routers]
  [http.routers.router-secure]
    rule = "Host(`example.com`)"
    service = "service-id"
    middlewares = ["hsts-header"]

    [http.routers.router-secure.tls]
      options = "modern"

  [http.routers.router-insecure]
    rule = "Host(`example.com`)"
    service = "service-id"
    middlewares = ["redirect-to-https", "hsts-header"]

[http.middlewares]
  [http.middlewares.redirect-to-https.redirectScheme]
    scheme = "https"
  [http.middlewares.hsts-header.headers]
    [http.middlewares.hsts-header.headers.customResponseHeaders]
      Strict-Transport-Security = "max-age=63072000"

# due to Go limitations, it is highly recommended that you use an ECDSA
# certificate, or you may experience compatibility issues
[[tls.certificates]]
  certFile = "/path/to/signed_cert_plus_intermediates"
  keyFile = "/path/to/private_key"

[tls.options]
  [tls.options.modern]
    minVersion = "VersionTLS13"