version: "3.7"

services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: php:7.4-apache
    build:
      context: ./config/php/
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./site:/var/www/html
      - ./logs:/usr/local/apache2/logs
      - ./config/apache/vhosts:/usr/local/apache2/conf/vhosts

networks:
  proxy:
    external: true