version: "3.7"

services:
  apache:
    image: 'httpd:2.4'
    container_name: apache
    ports:
      - '80:8080'
    volumes:
      - ./site:/var/www/html
      - ./config/apache/conf:/usr/local/apache2/conf
      - ./logs:/var/log/apache2
      

networks:
  proxy:
    external: true