http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - rate-limit
          - secured-headers

    chain-basic-auth:
      chain:
        middlewares:
          - rate-limit
          - secured-headers
          - basic-auth